package com.shop.po;
// Generated 2018-9-26 17:58:28 by Hibernate Tools 5.3.0.Beta2

import java.util.Date;

/**
 * CmsMenu generated by hbm2java
 */
public class CmsMenu implements java.io.Serializable {

	private Long menuId;
	private Long parentId;
	private Byte menuType;
	private String menuCode;
	private String menuName;
	private Integer sort;
	private String href;
	private String icon;
	private Byte status;
	private String permission;
	private Date createTime;
	private Date updateTime;
	private String remarks;

	public CmsMenu() {
	}

	public CmsMenu(Long parentId, Byte menuType, String menuCode, String menuName, Integer sort, String href,
			String icon, Byte status, String permission, Date createTime, Date updateTime, String remarks) {
		this.parentId = parentId;
		this.menuType = menuType;
		this.menuCode = menuCode;
		this.menuName = menuName;
		this.sort = sort;
		this.href = href;
		this.icon = icon;
		this.status = status;
		this.permission = permission;
		this.createTime = createTime;
		this.updateTime = updateTime;
		this.remarks = remarks;
	}

	public Long getMenuId() {
		return this.menuId;
	}

	public void setMenuId(Long menuId) {
		this.menuId = menuId;
	}

	public Long getParentId() {
		return this.parentId;
	}

	public void setParentId(Long parentId) {
		this.parentId = parentId;
	}

	public Byte getMenuType() {
		return this.menuType;
	}

	public void setMenuType(Byte menuType) {
		this.menuType = menuType;
	}

	public String getMenuCode() {
		return this.menuCode;
	}

	public void setMenuCode(String menuCode) {
		this.menuCode = menuCode;
	}

	public String getMenuName() {
		return this.menuName;
	}

	public void setMenuName(String menuName) {
		this.menuName = menuName;
	}

	public Integer getSort() {
		return this.sort;
	}

	public void setSort(Integer sort) {
		this.sort = sort;
	}

	public String getHref() {
		return this.href;
	}

	public void setHref(String href) {
		this.href = href;
	}

	public String getIcon() {
		return this.icon;
	}

	public void setIcon(String icon) {
		this.icon = icon;
	}

	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

	public String getPermission() {
		return this.permission;
	}

	public void setPermission(String permission) {
		this.permission = permission;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

}
