package com.shop.po;
// Generated 2018-9-26 17:58:28 by Hibernate Tools 5.3.0.Beta2

import java.util.Date;

/**
 * CmsRole generated by hbm2java
 */
public class CmsRole implements java.io.Serializable {

	private Long roleId;
	private String roleName;
	private String roleSign;
	private Byte isSystem;
	private Byte status;
	private Date createTime;
	private Date updateTime;
	private String remarks;

	public CmsRole() {
	}

	public CmsRole(String roleName, String roleSign, Byte isSystem, Byte status, Date createTime, Date updateTime,
			String remarks) {
		this.roleName = roleName;
		this.roleSign = roleSign;
		this.isSystem = isSystem;
		this.status = status;
		this.createTime = createTime;
		this.updateTime = updateTime;
		this.remarks = remarks;
	}

	public Long getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Long roleId) {
		this.roleId = roleId;
	}

	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	public String getRoleSign() {
		return this.roleSign;
	}

	public void setRoleSign(String roleSign) {
		this.roleSign = roleSign;
	}

	public Byte getIsSystem() {
		return this.isSystem;
	}

	public void setIsSystem(Byte isSystem) {
		this.isSystem = isSystem;
	}

	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

}
