package com.shop.po;
// Generated 2018-9-26 17:58:28 by Hibernate Tools 5.3.0.Beta2

import java.util.Date;

/**
 * CmsRoleMenu generated by hbm2java
 */
public class CmsRoleMenu implements java.io.Serializable {

	private Long roleMenuId;
	private Long roleId;
	private Long menuId;
	private Date createTime;

	public CmsRoleMenu() {
	}

	public CmsRoleMenu(Long roleId, Long menuId, Date createTime) {
		this.roleId = roleId;
		this.menuId = menuId;
		this.createTime = createTime;
	}

	public Long getRoleMenuId() {
		return this.roleMenuId;
	}

	public void setRoleMenuId(Long roleMenuId) {
		this.roleMenuId = roleMenuId;
	}

	public Long getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Long roleId) {
		this.roleId = roleId;
	}

	public Long getMenuId() {
		return this.menuId;
	}

	public void setMenuId(Long menuId) {
		this.menuId = menuId;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

}
