package com.shop.po;
// Generated 2018-9-26 17:58:28 by Hibernate Tools 5.3.0.Beta2

import java.util.Date;

/**
 * CmsUserRole generated by hbm2java
 */
public class CmsUserRole implements java.io.Serializable {

	private Long userRoleId;
	private Long roleId;
	private Long userId;
	private Date createTime;

	public CmsUserRole() {
	}

	public CmsUserRole(Long roleId, Long userId, Date createTime) {
		this.roleId = roleId;
		this.userId = userId;
		this.createTime = createTime;
	}

	public Long getUserRoleId() {
		return this.userRoleId;
	}

	public void setUserRoleId(Long userRoleId) {
		this.userRoleId = userRoleId;
	}

	public Long getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Long roleId) {
		this.roleId = roleId;
	}

	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

}
