package com.shop.po;
// Generated 2018-9-26 17:58:28 by Hibernate Tools 5.3.0.Beta2

import java.util.Date;

/**
 * OsAddress generated by hbm2java
 */
public class OsAddress implements java.io.Serializable {

	private Long addressId;
	private Long userId;
	private String userName;
	private String userTag;
	private String userPhone;
	private String userAdress;
	private Integer userZipcode;
	private Date createTime;
	private Date updateTime;

	public OsAddress() {
	}

	public OsAddress(Long userId, String userName, String userTag, String userPhone, String userAdress,
			Integer userZipcode, Date createTime, Date updateTime) {
		this.userId = userId;
		this.userName = userName;
		this.userTag = userTag;
		this.userPhone = userPhone;
		this.userAdress = userAdress;
		this.userZipcode = userZipcode;
		this.createTime = createTime;
		this.updateTime = updateTime;
	}

	public Long getAddressId() {
		return this.addressId;
	}

	public void setAddressId(Long addressId) {
		this.addressId = addressId;
	}

	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getUserTag() {
		return this.userTag;
	}

	public void setUserTag(String userTag) {
		this.userTag = userTag;
	}

	public String getUserPhone() {
		return this.userPhone;
	}

	public void setUserPhone(String userPhone) {
		this.userPhone = userPhone;
	}

	public String getUserAdress() {
		return this.userAdress;
	}

	public void setUserAdress(String userAdress) {
		this.userAdress = userAdress;
	}

	public Integer getUserZipcode() {
		return this.userZipcode;
	}

	public void setUserZipcode(Integer userZipcode) {
		this.userZipcode = userZipcode;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

}
