package com.shop.po;
// Generated 2018-9-26 17:58:28 by Hibernate Tools 5.3.0.Beta2

import java.util.Date;

/**
 * OsCategory generated by hbm2java
 */
public class OsCategory implements java.io.Serializable {

	private Long categoryId;
	private String name;
	private Date createTime;
	private Date updateTime;
	private String pageTitle;
	private String pageDescription;

	public OsCategory() {
	}

	public OsCategory(String name, Date createTime, Date updateTime,
			String pageTitle, String pageDescription, String pageKeyword, String remarks) {
		this.name = name;
		this.createTime = createTime;
		this.updateTime = updateTime;
		this.pageTitle = pageTitle;
		this.pageDescription = pageDescription;
	}

	public Long getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Long categoryId) {
		this.categoryId = categoryId;
	}


	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public String getPageTitle() {
		return this.pageTitle;
	}

	public void setPageTitle(String pageTitle) {
		  this.pageTitle = pageTitle == null ? null : pageTitle.trim();
	}

	public String getPageDescription() {
		return this.pageDescription;
	}

	public void setPageDescription(String pageDescription) {
		this.pageDescription = pageDescription == null ? null : pageDescription.trim();
	}

}
