package com.shop.po;
// Generated 2018-9-26 17:58:28 by Hibernate Tools 5.3.0.Beta2

import java.util.Date;

/**
 * OsCategory generated by hbm2java
 */
public class OsCategory implements java.io.Serializable {

	private Long categoryId;
	private Long parentId;
	private String name;
	private Integer sort;
	private Byte type;
	private Date createTime;
	private Date updateTime;
	private String pageTitle;
	private String pageDescription;
	private String pageKeyword;
	private String remarks;

	public OsCategory() {
	}

	public OsCategory(Long parentId, String name, Integer sort, Byte type, Date createTime, Date updateTime,
			String pageTitle, String pageDescription, String pageKeyword, String remarks) {
		this.parentId = parentId;
		this.name = name;
		this.sort = sort;
		this.type = type;
		this.createTime = createTime;
		this.updateTime = updateTime;
		this.pageTitle = pageTitle;
		this.pageDescription = pageDescription;
		this.pageKeyword = pageKeyword;
		this.remarks = remarks;
	}

	public Long getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Long categoryId) {
		this.categoryId = categoryId;
	}

	public Long getParentId() {
		return this.parentId;
	}

	public void setParentId(Long parentId) {
		this.parentId = parentId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	public Integer getSort() {
		return this.sort;
	}

	public void setSort(Integer sort) {
		this.sort = sort;
	}

	public Byte getType() {
		return this.type;
	}

	public void setType(Byte type) {
		this.type = type;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public String getPageTitle() {
		return this.pageTitle;
	}

	public void setPageTitle(String pageTitle) {
		  this.pageTitle = pageTitle == null ? null : pageTitle.trim();
	}

	public String getPageDescription() {
		return this.pageDescription;
	}

	public void setPageDescription(String pageDescription) {
		this.pageDescription = pageDescription == null ? null : pageDescription.trim();
	}

	public String getPageKeyword() {
		return this.pageKeyword;
	}

	public void setPageKeyword(String pageKeyword) {
		 this.pageKeyword = pageKeyword == null ? null : pageKeyword.trim();
	}

	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		  this.remarks = remarks == null ? null : remarks.trim();
	}

}
