package com.shop.po;
// Generated 2018-9-26 17:58:28 by Hibernate Tools 5.3.0.Beta2

import java.math.BigDecimal;
import java.util.Date;

/**
 * OsOrder generated by hbm2java
 */
public class OsOrder implements java.io.Serializable {

	private Long orderId;
	private Long orderNumber;
	private Long userId;
	private Byte orderStatus;
	private Date createTime;
	private BigDecimal orderAmount;
	private BigDecimal payAmount;
	private Integer buyNumber;

	public OsOrder() {
	}

	public OsOrder(Long orderNumber, Long userId, Byte orderStatus, Date createTime,
			 BigDecimal orderAmount, BigDecimal payAmount, Integer buyNumber) {
		this.orderNumber = orderNumber;
		this.userId = userId;
		this.orderStatus = orderStatus;
		this.createTime = createTime;
		this.orderAmount = orderAmount;
		this.payAmount = payAmount;
		this.buyNumber = buyNumber;
	}

	public Long getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Long orderId) {
		this.orderId = orderId;
	}

	public Long getOrderNumber() {
		return this.orderNumber;
	}

	public void setOrderNumber(Long orderNumber) {
		this.orderNumber = orderNumber;
	}

	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	public Byte getOrderStatus() {
		return this.orderStatus;
	}

	public void setOrderStatus(Byte orderStatus) {
		this.orderStatus = orderStatus;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public BigDecimal getOrderAmount() {
		return this.orderAmount;
	}

	public void  setOrderAmount(BigDecimal orderAmount) {
		this.orderAmount = orderAmount;
	}

	public BigDecimal getPayAmount() {
		return this.payAmount;
	}

	public void setPayAmount(BigDecimal payAmount) {
		this.payAmount = payAmount;
	}

	public Integer getBuyNumber() {
		return this.buyNumber;
	}

	public void setBuyNumber(Integer buyNumber) {
		this.buyNumber = buyNumber;
	}

}
