package com.shop.po;
// Generated 2018-9-26 17:58:28 by Hibernate Tools 5.3.0.Beta2

import java.util.Date;

/**
 * OsOrderStatus generated by hbm2java
 */
public class OsOrderStatus implements java.io.Serializable {

	private Long orderStatusId;
	private Long orderId;
	private Byte orderStatus;
	private Date createTime;
	private Byte createStatus;
	private String remarks;

	public OsOrderStatus() {
	}

	public OsOrderStatus(Long orderId, Byte orderStatus, Date createTime, Byte createStatus, String remarks) {
		this.orderId = orderId;
		this.orderStatus = orderStatus;
		this.createTime = createTime;
		this.createStatus = createStatus;
		this.remarks = remarks;
	}

	public Long getOrderStatusId() {
		return this.orderStatusId;
	}

	public void setOrderStatusId(Long orderStatusId) {
		this.orderStatusId = orderStatusId;
	}

	public Long getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Long orderId) {
		this.orderId = orderId;
	}

	public Byte getOrderStatus() {
		return this.orderStatus;
	}

	public void setOrderStatus(Byte orderStatus) {
		this.orderStatus = orderStatus;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Byte getCreateStatus() {
		return this.createStatus;
	}

	public void setCreateStatus(Byte createStatus) {
		this.createStatus = createStatus;
	}

	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

}
