package com.shop.po;
// Generated 2018-9-26 17:58:28 by Hibernate Tools 5.3.0.Beta2

import java.util.Date;

/**
 * OsOrderShipment generated by hbm2java
 */
public class OsOrderShipment implements java.io.Serializable {

	private Long orderShipmentId;
	private Long orderId;
	private String userName;
	private String userPhone;
	private String userAdress;
	private Integer userZipcode;
	private Date updateTime;

	public OsOrderShipment() {
	}

	public OsOrderShipment(Long orderId, String userName, String userPhone, String userAdress, Integer userZipcode,
			Date updateTime) {
		this.orderId = orderId;
		this.userName = userName;
		this.userPhone = userPhone;
		this.userAdress = userAdress;
		this.userZipcode = userZipcode;
		this.updateTime = updateTime;
	}

	public Long getOrderShipmentId() {
		return this.orderShipmentId;
	}

	public void setOrderShipmentId(Long orderShipmentId) {
		this.orderShipmentId = orderShipmentId;
	}

	public Long getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Long orderId) {
		this.orderId = orderId;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getUserPhone() {
		return this.userPhone;
	}

	public void setUserPhone(String userPhone) {
		this.userPhone = userPhone;
	}

	public String getUserAdress() {
		return this.userAdress;
	}

	public void setUserAdress(String userAdress) {
		this.userAdress = userAdress;
	}

	public Integer getUserZipcode() {
		return this.userZipcode;
	}

	public void setUserZipcode(Integer userZipcode) {
		this.userZipcode = userZipcode;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

}
