package com.shop.po;
// Generated 2018-9-26 17:58:28 by Hibernate Tools 5.3.0.Beta2

import java.util.Date;

/**
 * OsProductCategory generated by hbm2java
 */
public class OsProductCategory implements java.io.Serializable {

	private Long productCategoryId;
	private Long productId;
	private Long categoryId;
	private Date createTime;

	public OsProductCategory() {
	}

	public OsProductCategory(Long productId, Long categoryId, Date createTime) {
		this.productId = productId;
		this.categoryId = categoryId;
		this.createTime = createTime;
	}

	public Long getProductCategoryId() {
		return this.productCategoryId;
	}

	public void setProductCategoryId(Long productCategoryId) {
		this.productCategoryId = productCategoryId;
	}

	public Long getProductId() {
		return this.productId;
	}

	public void setProductId(Long productId) {
		this.productId = productId;
	}

	public Long getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Long categoryId) {
		this.categoryId = categoryId;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

}
