package com.shop.po;
// Generated 2018-9-26 17:58:28 by Hibernate Tools 5.3.0.Beta2

import java.util.Date;

/**
 * OsProductImage generated by hbm2java
 */
public class OsProductImage implements java.io.Serializable {

	private Long picImgId;
	private Long productId;
	private String picImg;
	private Byte sort;
	private Byte status;
	private Date createTime;

	public OsProductImage() {
	}

	public OsProductImage(Long productId, String picImg, Byte sort, Byte status, Date createTime) {
		this.productId = productId;
		this.picImg = picImg;
		this.sort = sort;
		this.status = status;
		this.createTime = createTime;
	}

	public Long getPicImgId() {
		return this.picImgId;
	}

	public void setPicImgId(Long picImgId) {
		this.picImgId = picImgId;
	}

	public Long getProductId() {
		return this.productId;
	}

	public void setProductId(Long productId) {
		this.productId = productId;
	}

	public String getPicImg() {
		return this.picImg;
	}

	public void setPicImg(String picImg) {
		  this.picImg = picImg == null ? null : picImg.trim();
	}

	public Byte getSort() {
		return this.sort;
	}

	public void setSort(Byte sort) {
		this.sort = sort;
	}

	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

}
