package com.shop.po;
// Generated 2018-9-26 17:58:28 by Hibernate Tools 5.3.0.Beta2

import java.math.BigDecimal;
import java.util.Date;

/**
 * OsProductSpecification generated by hbm2java
 */
public class OsProductSpecification implements java.io.Serializable {

	private Long productSpecId;
	private Long productSpecNumber;
	private Long productId;
	private String spec;
	private Integer stock;
	private Integer salesVolume;
	private BigDecimal price;
	private Integer score;
	private Byte defaultStatus;
	private Byte status;
	private Date createTime;
	private Date updateTime;

	public OsProductSpecification() {
	}

	public OsProductSpecification(Long productSpecNumber, Long productId, String spec, Integer stock,
			Integer salesVolume, BigDecimal price, Integer score, Byte defaultStatus, Byte status, Date createTime,
			Date updateTime) {
		this.productSpecNumber = productSpecNumber;
		this.productId = productId;
		this.spec = spec;
		this.stock = stock;
		this.salesVolume = salesVolume;
		this.price = price;
		this.score = score;
		this.defaultStatus = defaultStatus;
		this.status = status;
		this.createTime = createTime;
		this.updateTime = updateTime;
	}

	public Long getProductSpecId() {
		return this.productSpecId;
	}

	public void setProductSpecId(Long productSpecId) {
		this.productSpecId = productSpecId;
	}

	public Long getProductSpecNumber() {
		return this.productSpecNumber;
	}

	public void setProductSpecNumber(Long productSpecNumber) {
		this.productSpecNumber = productSpecNumber;
	}

	public Long getProductId() {
		return this.productId;
	}

	public void setProductId(Long productId) {
		this.productId = productId;
	}

	public String getSpec() {
		return this.spec;
	}

	public void setSpec(String spec) {
		 this.spec = spec == null ? null : spec.trim();
	}

	public Integer getStock() {
		return this.stock;
	}

	public void setStock(Integer stock) {
		this.stock = stock;
	}

	public Integer getSalesVolume() {
		return this.salesVolume;
	}

	public void setSalesVolume(Integer salesVolume) {
		this.salesVolume = salesVolume;
	}

	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	public Integer getScore() {
		return this.score;
	}

	public void setScore(Integer score) {
		this.score = score;
	}

	public Byte getDefaultStatus() {
		return this.defaultStatus;
	}

	public void setDefaultStatus(Byte defaultStatus) {
		this.defaultStatus = defaultStatus;
	}

	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

}
