package com.shop.po;
// Generated 2018-9-26 17:58:28 by Hibernate Tools 5.3.0.Beta2

import java.util.Date;

/**
 * OsSpecificationAttribute generated by hbm2java
 */
public class OsSpecificationAttribute implements java.io.Serializable {

	private Long specAttrId;
	private Long specificationId;
	private String name;
	private Date createTime;

	public OsSpecificationAttribute() {
	}

	public OsSpecificationAttribute(Long specificationId, String name, Date createTime) {
		this.specificationId = specificationId;
		this.name = name;
		this.createTime = createTime;
	}

	public Long getSpecAttrId() {
		return this.specAttrId;
	}

	public void setSpecAttrId(Long specAttrId) {
		this.specAttrId = specAttrId;
	}

	public Long getSpecificationId() {
		return this.specificationId;
	}

	public void setSpecificationId(Long specificationId) {
		this.specificationId = specificationId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		 this.name = name == null ? null : name.trim();
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

}
