package com.shop.po;
// Generated 2018-9-26 17:58:28 by Hibernate Tools 5.3.0.Beta2

import java.util.Date;

/**
 * OsUser generated by hbm2java
 */
public class OsUser implements java.io.Serializable {

	private Long userId;
	private Long userNumber;
	private String userName;
	private String loginPassword;
	private String realName;
	private Boolean sex;
	private Byte age;
	private String picImg;
	private Boolean status;
	private String telephone;
	private Date regeistTime;
	private Date updateTime;

	public OsUser() {
	}

	public OsUser(Long userNumber, String userName, String loginPassword, String realName, Boolean sex, Byte age,
			String picImg, Boolean status, String telephone, Date regeistTime, Date updateTime) {
		this.userNumber = userNumber;
		this.userName = userName;
		this.loginPassword = loginPassword;
		this.realName = realName;
		this.sex = sex;
		this.age = age;
		this.picImg = picImg;
		this.status = status;
		this.telephone = telephone;
		this.regeistTime = regeistTime;
		this.updateTime = updateTime;
	}

	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	public Long getUserNumber() {
		return this.userNumber;
	}

	public void setUserNumber(Long userNumber) {
		this.userNumber = userNumber;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
	}

	public String getLoginPassword() {
		return this.loginPassword;
	}

	public void setLoginPassword(String loginPassword) {
        this.loginPassword = loginPassword == null ? null : loginPassword.trim();
	}

	public String getRealName() {
		return this.realName;
	}

	public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
	}

	public Boolean getSex() {
		return this.sex;
	}

	public void setSex(Boolean sex) {
		this.sex = sex;
	}

	public Byte getAge() {
		return this.age;
	}

	public void setAge(Byte age) {
		this.age = age;
	}

	public String getPicImg() {
		return this.picImg;
	}

	public void setPicImg(String picImg) {
        this.picImg = picImg == null ? null : picImg.trim();
	}

	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
	}

	public Date getRegeistTime() {
		return this.regeistTime;
	}

	public void setRegeistTime(Date regeistTime) {
		this.regeistTime = regeistTime;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

}
