package com.shop.vo;
// Generated 2018-9-26 17:58:28 by Hibernate Tools 5.3.0.Beta2

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

/**
 * OsProduct generated by hbm2java
 */
public class ProductVO implements java.io.Serializable {

	private Long productId;
	private Long categoryId ;
	private Long productNumber;
	private String name;
	private BigDecimal showPrice;
	private String introduce;
	private String picImg;
	private Date createTime;
	private Date updateTime;
	private String pageTitle;
	private String pageDescription;
	private String remarks;
	private String detailImg;
	private List<ProductVO> productVOs;
	   public List<ProductVO> getproductVOs() {
			return productVOs;
		}

	    public void setproductVOs(List<ProductVO> productVOs) {
			this.productVOs = productVOs;
		}
	public ProductVO() {
	}

	public ProductVO(Long categoryId, Long productNumber, String name, BigDecimal showPrice, String introduce, String picImg,
			Date createTime, Date updateTime, String pageTitle, String pageDescription, String remarks,String detailImg) {
		this.categoryId = categoryId;
		this.productNumber = productNumber;
		this.name = name;
		this.showPrice = showPrice;
		this.introduce = introduce;
		this.picImg = picImg;
		this.createTime = createTime;
		this.updateTime = updateTime;
		this.pageTitle = pageTitle;
		this.pageDescription = pageDescription;
		this.remarks = remarks;
		this.detailImg = detailImg;
	}

	public Long getProductId() {
		return this.productId;
	}
	
	public Long getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Long categoryId) {
		this.categoryId = categoryId;
	}
	
	public void setProductId(Long productId) {
		this.productId = productId;
	}

	public Long getProductNumber() {
		return this.productNumber;
	}

	public void setProductNumber(Long productNumber) {
		this.productNumber = productNumber;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name == null ? null:name.trim();
	}

	public BigDecimal getShowPrice() {
		return this.showPrice;
	}

	public void setShowPrice(BigDecimal showPrice) {
		this.showPrice = showPrice;
	}

	public String getIntroduce() {
		return this.introduce;
	}

	public void setIntroduce(String introduce) {
		this.introduce = introduce == null? null:introduce.trim();
	}

	public String getPicImg() {
		return this.picImg;
	}

	public void setPicImg(String picImg) {
		this.picImg = picImg == null ? null : picImg.trim();
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public String getPageTitle() {
		return this.pageTitle;
	}

	public void setPageTitle(String pageTitle) {
		this.pageTitle = pageTitle == null ? null : pageTitle.trim();
	}

	public String getPageDescription() {
		return this.pageDescription;
	}

	public void setPageDescription(String pageDescription) {
		this.pageDescription = pageDescription == null ? null : pageDescription.trim();
	}
	public String getRemarks() {
		return this.remarks;
	}
	public void setRemarks(String remarks) {
		this.remarks =remarks == null ? null : remarks.trim();
	}

	public String getDetailImg() {
		return this.detailImg;
	}
	public void setDetailImg(String detailImg) {
		this.detailImg =detailImg == null ? null : detailImg.trim();
	}


}
